from bidi.algorithm import get_display
import unicodedata

def normalize_hebrew(text):
    """Normalize and format Hebrew text for proper RTL display."""
    if not text:
        return text
    return get_display(unicodedata.normalize("NFKC", text.strip()))

DOCUMENT_CATEGORY_MAPPING = {
    1: normalize_hebrew("כתב תביעה"),
    2: normalize_hebrew("מסמך מזהה"),
    3: normalize_hebrew("הוכחת נישואין שרעי"),
    4: normalize_hebrew("ייפוי כוח"),
    5: normalize_hebrew("כתב מינוי סיוע משפטי"),
    6: normalize_hebrew("הסכמה על סמכות בית הדין השרעי"),
    7: normalize_hebrew("פרטי המנוח והיורשים"),
    8: normalize_hebrew("הסכם גירושין"),
    9: normalize_hebrew("תעודת פטירה"),
    10: normalize_hebrew("תצהיר הסתלקות מהירושה"),
    11: normalize_hebrew("מסמכים נוספים"),
    12: normalize_hebrew("מסמכים נוספים להוכחת נישואין"),
    13: normalize_hebrew("אישור תשלום שירות פרסום"),
    14: normalize_hebrew("הסכמה על סמכות בית הדין הדרוזי"),
    15: normalize_hebrew("הוכחת נישואין דרוזי"),
    16: normalize_hebrew("כתב תביעה"),
    17: normalize_hebrew("כתב בקשה"),
    18: normalize_hebrew("אישור תשלום שירות פרסום"),
    19: normalize_hebrew("תצהיר מבקשים"),
    20: normalize_hebrew("מסמך מזהה"),
    21: normalize_hebrew("מסמכים נוספים"),
    22: normalize_hebrew("תצהיר הסתלקות מהירושה"),
    23: normalize_hebrew("כתב מינוי מנהל עזבון"),
    24: normalize_hebrew("השלמת מסמכים שרעיים"),
    25: normalize_hebrew("תגובה"),
    26: normalize_hebrew("כתב הגנה"),
    27: normalize_hebrew("בקשה"),
    28: normalize_hebrew("כתב תביעה"),
    29: normalize_hebrew("פטור מאגרה"),
    30: normalize_hebrew("השלמת מסמכים דרוזים"),
    31: normalize_hebrew("כתב תביעה"),
    32: normalize_hebrew("כתב תביעה לסכסוך משפחתי"),
    33: normalize_hebrew("כתב בקשה ליישוב סכסוך"),
    34: normalize_hebrew("השלמת מסמכים מקרקעין"),
    35: normalize_hebrew("אישור יישוב סכסוך"),
    36: normalize_hebrew("כתב תביעה שכנגד"),
    37: normalize_hebrew("הודעה לצד ג'"),
    38: normalize_hebrew("צירוף מסמך אישור תשלום אגרה"),
    39: normalize_hebrew("השלמת מסמכים בתיק מקרקעין סטטוס לא תקין"),
    40: normalize_hebrew("כתב הגנה במקרקעין"),
    41: normalize_hebrew("מסמך תגובה במקרקעין"),
    42: normalize_hebrew("ייפוי כח"),
    43: normalize_hebrew("מסמכים לפעולה לגורם חדש בתיק"),
    44: normalize_hebrew("מזונות אישה - החזר הוצאות"),
    45: normalize_hebrew("מזונות אישה - שכ\"ד"),
    46: normalize_hebrew("חוזה נישואין"),
    47: normalize_hebrew("החלטת מזונות עדכנית"),
    48: normalize_hebrew("תעודת גירושין / החלטת גירושין"),
    49: normalize_hebrew("מסמכים נוספים להוכחת נישואין / גירושין"),
    50: normalize_hebrew("מסמכים רפואיים"),
    51: normalize_hebrew("הסכמה למינוי אפוטרופוס"),
    52: normalize_hebrew("החלטה למינוי אפוטרופוס"),
    53: normalize_hebrew("תעודת גירושין"),
    54: normalize_hebrew("מסמך צוואה"),
    55: normalize_hebrew("תמצית רישום"),
    59: normalize_hebrew("צו למינוי אפוטרופוס"),
    60: normalize_hebrew("תצהיר לאימות העובדות"),
    61: normalize_hebrew("כתב הסכמה לסמכות בית הדין"),
    62: normalize_hebrew("נימוקי הערר"),
    63: normalize_hebrew("החלטת רשות המיסים בהשגה"),
    64: normalize_hebrew("הצהרת העורר"),
    65: normalize_hebrew("בקשה לאיסור פרסום ודיון בדלתיים סגורות"),
    66: normalize_hebrew("פרוטוקול בעלי מניות"),
    67: normalize_hebrew("מסמכים נוספים - בי\"ד לעסקים"),
    68: normalize_hebrew("השלמת מסמכים - עסקים (קורונה וחרבות ברזל)"),
    69: normalize_hebrew("בקשה להארכת מועד להגשת ערר"),
    70: normalize_hebrew("בקשה להארכת מועד"),
    71: normalize_hebrew("בקשה לסילוק על הסף"),
    72: normalize_hebrew("בקשה לצירוף מסמכים"),
    73: normalize_hebrew("בקשה למחיקת ערר"),
    74: normalize_hebrew("בקשה למתן החלטה"),
    75: normalize_hebrew("בקשה לקביעת/ שינוי/ ביטול מועד דיון"),
    76: normalize_hebrew("בקשה לביטול/ תיקון החלטה"),
    77: normalize_hebrew("בקשה לפסיקת הוצאות"),
    78: normalize_hebrew("בקשה לאחר סגירת התיק"),
    79: normalize_hebrew("בקשה לעדכון פרטי מייצג/ עד"),
    80: normalize_hebrew("בקשה לאיסור פרסום החלטה ודיון בדלתיים סגורות"),
    81: normalize_hebrew("בקשה לאיחוד עררים"),
    82: normalize_hebrew("בקשה למתן תוקף של החלטה לפשרה"),
    83: normalize_hebrew("בקשה לעיכוב ביצוע החלטה"),
    84: normalize_hebrew("כתב תשובה בבית דין לעסקים"),
    87: normalize_hebrew("בקשה להחלפת מייצג"),
}
